[build-system]
requires = [ "poetry>=1.0.0",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "ERPLibre"
version = "1.1.0"
description = "Easy way to configure Odoo community"
license = "AGPL-3.0-or-later"
authors = [ "Mathieu Benoit <mathben@technolibre.ca>", "Alexandre Ferreira Benevides <afbenevides@technolibre.ca>",]

[tool.poetry.dependencies]
python = "^3.7"
Babel = "^2.3.4"
Jinja2 = "^2.10.1"
Mako = "^1.0.4"
MarkupSafe = "^0.23"
Pillow = "^6.1.0"
PyPDF2 = "^1.26.0"
PyYAML = "^5.3.1"
SOAPpy = "^0.12.22"
Voicent-Python = "^1.0"
Werkzeug = "^0.11.15"
XlsxWriter = "^0.9.3"
agithub = "^2.2.2"
altair = "^4.1.0"
bokeh = "^1.1.0"
chardet = "^3.0.4"
cython = "^0.29.21"
ddt = "^1.2.0"
decorator = "^4.0.10"
docutils = "^0.12"
ebaysdk = "^2.1.5"
email_validator = "^1.1.1"
extract-msg = "^0.24.4"
factur-x = "^1.12"
feedparser = "^5.2.1"
freezegun = "^0.3.10"
gevent = "^1.3.4"
gitpython = "^3.1.7"
giturlparse = "^0.9.2"
greenlet = "^0.4.13"
html2text = "^2016.9.19"
invoice2data = "^0.3.5"
iscompatible = "^0.1.1"
lasso = "^0.0.5"
libsass = "^0.12.3"
lxml = "^4.2.3"
matplotlib = ">=2.0.0"
mock = "^2.0.0"
mpld3 = "^0.3"
num2words = "^0.5.6"
numpy = "^1.19.1"
"oca.decorators" = "^0.0.1"
ofxparse = "^0.16"
openpyxl = "^3.0.4"
openupgradelib = "^2.0.0"
passlib = "^1.6.5"
pdf2image = "^1.13.1"
phonenumbers = "^8.12.7"
plotly = "^4.1.0"
premailer = "^3.7.0"
psutil = "^4.3.1"
psycopg2 = "^2.7.3.1"
py-Asterisk = "^0.5.18"
"py3o.formats" = "^0.3"
"py3o.template" = "^0.10.0"
pycountry = "^20.7.3"
pydot = "^1.2.3"
pygount = "<1.2.0"
pyldap = "^2.4.28"
pyotp = "^2.3.0"
pyparsing = "^2.1.10"
pyserial = "^3.1.1"
pysftp = "^0.2.9"
python-dateutil = "^2.5.3"
python-u2flib-server = "^5.0.0"
pytz = "^2016.7"
pyusb = "^1.0.0"
pyzbar = "^0.1.8"
qrcode = "^5.3"
raven = "^6.10.0"
reportlab = "^3.3.0"
requests = "^2.20.0"
retrying = "^1.3.3"
sphinx = ">=1.6.7"
sphinx-patchqueue = ">=1.0"
suds-jurko = "^0.6"
toml = "^0.10.1"
unidecode = "^1.0.22"
vatnumber = "^1.2"
vobject = "^0.9.3"
websocket-client = "^0.57.0"
wheel = "^0.34.2"
xlrd = "^1.0.0"
xlwt = "^1.3"
xmltodict = "^0.12.0"
zxcvbn = "^4.4.28"

[tool.poetry.dev-dependencies]
websocket_client = "^0.57.0"
